apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: "{{ name }}"
  labels:
    {%- for key, value in skills.items() %}
    {{ key }}: "{{ value }}"
    {%- endfor %}
spec:
  serviceAccountName: "{{ name }}"
  description: "{{ description }}"
  type: BYO
  byo:
    deployment:
      image: agent/custom/template-agent:0.1.0
      env:
        - name: DB_URI
          value: "postgresql://postgres:postgres@postgres.database.svc.cluster.local:5432/ai_platform_core?sslmode=verify-ca"
        - name: AGENT_HOST
          value: "0.0.0.0"
        - name: AGENT_PORT
          value: "8080"
        - name: AGENT_NAME
          value: "{{ name }}"
        - name: DB_CA_CONTENT
          valueFrom:
            secretKeyRef:
              name: postgres-tls
              key: ca.crt
        - name: DB_CERT_CONTENT
          valueFrom:
            secretKeyRef:
              name: postgres-tls
              key: tls.crt
        - name: DB_KEY_CONTENT
          valueFrom:
            secretKeyRef:
              name: postgres-tls
              key: tls.key
        - name: OPENAI_API_KEY
          value: YOUR_KEY