apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-agent-control-plane
  namespace: kagent
  labels:
    app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
      - name: mcp-container
        image: mcp-agent-control-plane:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3050
          name: mcp-port
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  namespace: kagent
spec:
  selector:
    app: mcp-server
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3050
  type: ClusterIP