apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-agent-control-plane
  namespace: kagent
  labels:
    kagent.dev/discovery : "disabled"
spec:
  transportType: "http"
  httpTransport:
    targetPort: 3050
    path: 0.0.0.0
  deployment:
    image: "mcp-agent-control-plane:0.1.0"
    imagePullPolicy: IfNotPresent
    port: 3050
    env:
      PORT: "3050"
      HOST: "0.0.0.0"
      MCP_TRANSPORT_MODE: "http"