apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: controller
spec:
  parentRefs:
  - name: agentgateway-proxy
    namespace: agentgateway-system
  rules:
  - backendRefs:
      - name: kagent-controller
        port: 8083
