apiVersion: v2
name: infrastructure-umbrella
description: A main chart to deploy the entire agent gateway stack
version: 1.0.0
type: application

dependencies:
  # OCI Charts
  - name: agentgateway-crds
    version: "v2.2.1"
    repository: "oci://ghcr.io/kgateway-dev/charts"
  - name: kagent-crds
    version: "1.0.0"
    repository: "oci://ghcr.io/kagent-dev/kagent/helm"

  # Local Charts (Usa la ruta relativa a la carpeta /charts)
  - name: keycloak
    version: 0.1.0
    repository: "file://../keycloak"
  - name: agentgateway
    version: 0.1.0
    repository: "file://../agentgateway-install"
  - name: cert-manager
    version: 0.1.0
    repository: "file://../cert-manager"
  - name: postgresql
    version: 0.1.0
    repository: "file://../postgresql"
  - name: loki
    version: 0.1.0
    repository: "file://../loki"
  # ... repite para grafana, tempo, etc.
