apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  namespace: kagent
  name: orchestrator-agent
  labels:
spec:
  description: "control agent that provisions and governs subordinate tutor agents. It handles orchestration workflows, task routing, state management, and inter-agent communication to maintain scalable and structured execution across the system."
  type: BYO
  byo:
    deployment:
      image: agent/custom/orchestrator:0.1.0
      env:
        - name: MCP_SERVER_URL
          value: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:80/mcp-server"
        - name: DB_URI
          value: "postgresql://postgres:postgres@postgres.database.svc.cluster.local:5432/ai_platform_core"
        - name: AGENT_HOST
          value: "0.0.0.0"
        - name: AGENT_PORT
          value: "8080"

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetry-collector-audit.telemetry.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: grpc
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://opentelemetry-collector-audit.telemetry.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
          value: "http://opentelemetry-collector-audit.telemetry.svc.cluster.local:4317"
        - name: LANGSMITH_TRACING
          value: "false"
        - name: OTEL_SERVICE_NAME
          value: "langgraph-app"

        - name: API_KEY
          value: "your-token"
        - name: PROVIDER
          value: "openai"
        - name: MODEL
          value: "gpt-4o-mini"

        - name: AGENT_USERNAME
          value: "agent"
        - name: AGENT_PASSWORD
          value: "1234"
        - name: CLIENT_ID
          value: "agent-client"
        - name: TOKEN_ENDPOINT
          value: "http://keycloak.keycloak.svc.cluster.local:8080/realms/agent-realm/protocol/openid-connect/token"
