apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-agent-manager-role
rules:
- apiGroups: ["kagent.dev"]
  resources: ["agents", "agents/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "create", "update"]

- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "create", "update"]
