apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-cert
  namespace: database
spec:
  secretName: postgres-tls
  issuerRef:
    name: city-ca
    kind: ClusterIssuer
  commonName: postgres
  dnsNames:
  - postgres.database.svc.cluster.local