apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: jwt-auth-policy-global
  namespace: agentgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: agentgateway-proxy
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: "http://keycloak.keycloak.svc.cluster.local:8080/realms/{{ .Values.keycloak_realm }}"
        audiences:
          - {{ .Values.jwt_audiencepolicy | quote }}
        jwks:
          remote:
            jwksPath: "/realms/{{ .Values.keycloak_realm }}/protocol/openid-connect/certs"
            cacheDuration: "5m"
            backendRef:
              group: ""
              kind: Service
              name: keycloak
              namespace: keycloak
              port: 8080